# 03 - Indexing and Selecting Data
How do we pick the columns / rows we want?

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "name":  ["Arun", "Bala", "Chitra", "Divya", "Elango"],
    "dept":  ["CSE", "ECE", "CSE", "IT", "MECH"],
    "marks": [78, 65, 88, 72, 55],
    "city":  ["Chennai", "Madurai", "Chennai", "Coimbatore", "Trichy"],
})
df

     name  dept  marks        city
0    Arun   CSE     78     Chennai
1    Bala   ECE     65     Madurai
2  Chitra   CSE     88     Chennai
3   Divya    IT     72  Coimbatore
4  Elango  MECH     55      Trichy

## 1. Select columns

In [3]:
df["name"]              # one column -> Series

0      Arun
1      Bala
2    Chitra
3     Divya
4    Elango
Name: name, dtype: str

In [4]:
df[["name", "marks"]]   # many columns -> DataFrame (note the double brackets)

     name  marks
0    Arun     78
1    Bala     65
2  Chitra     88
3   Divya     72
4  Elango     55

## 2. `iloc` - select by **position** (0, 1, 2 ...)

In [5]:
print(df.iloc[0])           # first row

name        Arun
dept         CSE
marks         78
city     Chennai
Name: 0, dtype: object

In [6]:
df.iloc[1:3]               # rows 1 and 2 (end is NOT included)

     name dept  marks     city
1    Bala  ECE     65  Madurai
2  Chitra  CSE     88  Chennai

In [7]:
df.iloc[0:3, 0:2]          # rows 0-2, columns 0-1

     name dept
0    Arun  CSE
1    Bala  ECE
2  Chitra  CSE

## 3. `loc` - select by **label**

In [8]:
df.loc[2]                         # row with index label 2

name      Chitra
dept         CSE
marks         88
city     Chennai
Name: 2, dtype: object

In [9]:
df.loc[0:2, ["name", "marks"]]   # loc INCLUDES the end label

     name  marks
0    Arun     78
1    Bala     65
2  Chitra     88

## 4. Boolean filtering (conditions)

In [10]:
df[df["marks"] > 70]

     name dept  marks        city
0    Arun  CSE     78     Chennai
2  Chitra  CSE     88     Chennai
3   Divya   IT     72  Coimbatore

In [11]:
df[df["dept"] == "CSE"]

     name dept  marks     city
0    Arun  CSE     78  Chennai
2  Chitra  CSE     88  Chennai

Combine conditions with `&` (and), `|` (or). Each condition needs its own brackets.

In [12]:
df[(df["dept"] == "CSE") & (df["marks"] > 80)]

     name dept  marks     city
2  Chitra  CSE     88  Chennai

In [13]:
df[(df["city"] == "Chennai") | (df["marks"] < 60)]

     name  dept  marks     city
0    Arun   CSE     78  Chennai
2  Chitra   CSE     88  Chennai
4  Elango  MECH     55   Trichy

In [14]:
df[df["dept"].isin(["CSE", "IT"])]

     name dept  marks        city
0    Arun  CSE     78     Chennai
2  Chitra  CSE     88     Chennai
3   Divya   IT     72  Coimbatore

## 5. Use a column as the index

In [15]:
df2 = df.set_index("name")
df2

        dept  marks        city
name
Arun     CSE     78     Chennai
Bala     ECE     65     Madurai
Chitra   CSE     88     Chennai
Divya     IT     72  Coimbatore
Elango  MECH     55      Trichy

In [16]:
df2.loc["Chitra", "marks"]

np.int64(88)

## Practice on the real data

In [17]:
students = pd.read_csv("data/students.csv")
students[(students["dept"] == "IT") & (students["marks"] > 70)]

     name dept gender  age  marks  attendance        city
3   Divya   IT      F   22     72          85  Coimbatore
9  Janani   IT      F   21     95          99     Chennai

## Try it yourself
1. Show `name` and `city` of students from `MECH`.
2. Show students with attendance below 75.
3. Show rows 5 to 9 using `iloc`.

In [18]:
# your code here