# 04 - Row and Column Operations
Add, rename, delete, sort and combine.

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "name":  ["Arun", "Bala", "Chitra", "Divya"],
    "maths": [78, 65, 88, 72],
    "physics": [70, 60, 90, 68],
})
df

     name  maths  physics
0    Arun     78       70
1    Bala     65       60
2  Chitra     88       90
3   Divya     72       68

## 1. Add a new column

In [3]:
df["total"] = df["maths"] + df["physics"]
df["average"] = df["total"] / 2
df

     name  maths  physics  total  average
0    Arun     78       70    148     74.0
1    Bala     65       60    125     62.5
2  Chitra     88       90    178     89.0
3   Divya     72       68    140     70.0

In [4]:
df["result"] = "Pass"                      # same value for all rows
df.loc[df["average"] < 65, "result"] = "Fail"   # change some rows
df

     name  maths  physics  total  average result
0    Arun     78       70    148     74.0   Pass
1    Bala     65       60    125     62.5   Fail
2  Chitra     88       90    178     89.0   Pass
3   Divya     72       68    140     70.0   Pass

## 2. Rename columns

In [5]:
df = df.rename(columns={"maths": "math_marks", "physics": "physics_marks"})
df

     name  math_marks  physics_marks  total  average result
0    Arun          78             70    148     74.0   Pass
1    Bala          65             60    125     62.5   Fail
2  Chitra          88             90    178     89.0   Pass
3   Divya          72             68    140     70.0   Pass

## 3. Drop (delete) columns

In [6]:
df = df.drop(columns=["result"])
df

     name  math_marks  physics_marks  total  average
0    Arun          78             70    148     74.0
1    Bala          65             60    125     62.5
2  Chitra          88             90    178     89.0
3   Divya          72             68    140     70.0

## 4. Sort rows

In [7]:
df.sort_values("total")

     name  math_marks  physics_marks  total  average
1    Bala          65             60    125     62.5
3   Divya          72             68    140     70.0
0    Arun          78             70    148     74.0
2  Chitra          88             90    178     89.0

In [8]:
df.sort_values("total", ascending=False)

     name  math_marks  physics_marks  total  average
2  Chitra          88             90    178     89.0
0    Arun          78             70    148     74.0
3   Divya          72             68    140     70.0
1    Bala          65             60    125     62.5

## 5. Add a new row

In [9]:
new_row = pd.DataFrame({
    "name": ["Elango"], "math_marks": [55], "physics_marks": [50],
    "total": [105], "average": [52.5],
})
df = pd.concat([df, new_row], ignore_index=True)
df

     name  math_marks  physics_marks  total  average
0    Arun          78             70    148     74.0
1    Bala          65             60    125     62.5
2  Chitra          88             90    178     89.0
3   Divya          72             68    140     70.0
4  Elango          55             50    105     52.5

## 6. Drop a row (by index label)

In [10]:
df = df.drop(1)         # removes the row with index 1 (Bala)
df

     name  math_marks  physics_marks  total  average
0    Arun          78             70    148     74.0
2  Chitra          88             90    178     89.0
3   Divya          72             68    140     70.0
4  Elango          55             50    105     52.5

In [11]:
df = df.reset_index(drop=True)    # make the index 0,1,2... again
df

     name  math_marks  physics_marks  total  average
0    Arun          78             70    148     74.0
1  Chitra          88             90    178     89.0
2   Divya          72             68    140     70.0
3  Elango          55             50    105     52.5

## Practice on the real data

In [12]:
students = pd.read_csv("data/students.csv")
students["marks_out_of_10"] = students["marks"] / 10
students = students.rename(columns={"attendance": "attendance_pct"})
students.sort_values("marks", ascending=False).head(5)

       name dept gender  age  marks  attendance_pct     city  marks_out_of_10
9    Janani   IT      F   21     95              99  Chennai              9.5
15    Priya  CSE      F   21     93              97  Madurai              9.3
5   Fathima  ECE      F   21     91              98  Chennai              9.1
2    Chitra  CSE      F   21     88              95  Chennai              8.8
14     Omar  ECE      M   23     87              93  Chennai              8.7

## Try it yourself
1. Add a column `eligible` that is `True` when `attendance_pct >= 75`.
2. Drop the `gender` column.
3. Show the bottom 3 students by marks.

In [13]:
# your code here