# 05 - The `apply()` Function
`apply()` runs **your own function** on every value (or every row) of a column.
Use it when pandas has no ready-made method for what you want.

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "name":  ["Arun", "Bala", "Chitra", "Divya", "Elango"],
    "marks": [78, 45, 88, 72, 91],
    "attendance": [92, 80, 95, 70, 98],
})
df

     name  marks  attendance
0    Arun     78          92
1    Bala     45          80
2  Chitra     88          95
3   Divya     72          70
4  Elango     91          98

## 1. apply with a normal function

In [3]:
def get_grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 75:
        return "B"
    elif marks >= 50:
        return "C"
    else:
        return "Fail"

df["grade"] = df["marks"].apply(get_grade)
df

     name  marks  attendance grade
0    Arun     78          92     B
1    Bala     45          80  Fail
2  Chitra     88          95     B
3   Divya     72          70     C
4  Elango     91          98     A

## 2. apply with a lambda (one-line function)

In [4]:
df["marks_out_of_10"] = df["marks"].apply(lambda m: m / 10)
df

     name  marks  attendance grade  marks_out_of_10
0    Arun     78          92     B              7.8
1    Bala     45          80  Fail              4.5
2  Chitra     88          95     B              8.8
3   Divya     72          70     C              7.2
4  Elango     91          98     A              9.1

In [5]:
df["name_upper"] = df["name"].apply(lambda n: n.upper())
df

     name  marks  attendance grade  marks_out_of_10 name_upper
0    Arun     78          92     B              7.8       ARUN
1    Bala     45          80  Fail              4.5       BALA
2  Chitra     88          95     B              8.8     CHITRA
3   Divya     72          70     C              7.2      DIVYA
4  Elango     91          98     A              9.1     ELANGO

## 3. apply on rows - use `axis=1`

In [6]:
def check_eligible(row):
    if row["marks"] >= 50 and row["attendance"] >= 75:
        return "Eligible"
    return "Not eligible"

df["exam_status"] = df.apply(check_eligible, axis=1)
df

     name  marks  attendance grade  marks_out_of_10 name_upper   exam_status
0    Arun     78          92     B              7.8       ARUN      Eligible
1    Bala     45          80  Fail              4.5       BALA  Not eligible
2  Chitra     88          95     B              8.8     CHITRA      Eligible
3   Divya     72          70     C              7.2      DIVYA  Not eligible
4  Elango     91          98     A              9.1     ELANGO      Eligible

## 4. `map()` - replace values using a dictionary

In [7]:
df["grade_points"] = df["grade"].map({"A": 10, "B": 8, "C": 6, "Fail": 0})
df

,name,marks,attendance,grade,marks_out_of_10,name_upper,exam_status,grade_points
0,Arun,78,92,B,7.8,ARUN,Eligible,8
1,Bala,45,80,Fail,4.5,BALA,Not eligible,0
2,Chitra,88,95,B,8.8,CHITRA,Eligible,8
3,Divya,72,70,C,7.2,DIVYA,Not eligible,6
4,Elango,91,98,A,9.1,ELANGO,Eligible,10

## Practice on the real data
Tip: for simple things like `marks / 10`, direct arithmetic is faster than `apply`.
Use `apply` when you need `if / else` logic.

In [8]:
students = pd.read_csv("data/students.csv")
students["grade"] = students["marks"].apply(get_grade)
students[["name", "marks", "grade"]].head(8)

      name  marks grade
0     Arun     78     B
1     Bala     65     C
2   Chitra     88     B
3    Divya     72     C
4   Elango     55     C
5  Fathima     91     A
6    Gokul     60     C
7     Hema     84     B

## Try it yourself
1. Write a function `attendance_level` returning "Good" (>=90), "Average" (75-89) or "Low".
2. Apply it on `students["attendance"]`.
3. Use `apply(axis=1)` to create a sentence like `"Arun from CSE scored 78"`.

In [9]:
# your code here