# 06 - Grouping with `groupby()`
Split the data into groups → calculate something for each group → show the result.
Example: *average marks of each department*.

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "name":   ["Arun", "Bala", "Chitra", "Divya", "Elango", "Fathima"],
    "dept":   ["CSE", "ECE", "CSE", "IT", "ECE", "CSE"],
    "gender": ["M", "M", "F", "F", "M", "F"],
    "marks":  [78, 65, 88, 72, 55, 91],
})
df

      name dept gender  marks
0     Arun  CSE      M     78
1     Bala  ECE      M     65
2   Chitra  CSE      F     88
3    Divya   IT      F     72
4   Elango  ECE      M     55
5  Fathima  CSE      F     91

## 1. Group and calculate

In [3]:
df.groupby("dept")["marks"].mean()

dept
CSE    85.666667
ECE    60.000000
IT     72.000000
Name: marks, dtype: float64

In [4]:
df.groupby("dept")["marks"].max()

dept
CSE    91
ECE    65
IT     72
Name: marks, dtype: int64

In [5]:
df.groupby("dept")["marks"].sum()

dept
CSE    257
ECE    120
IT      72
Name: marks, dtype: int64

## 2. Count the members of each group

In [6]:
df.groupby("dept").size()

dept
CSE    3
ECE    2
IT     1
dtype: int64

## 3. Many calculations at once with `agg`

In [7]:
df.groupby("dept")["marks"].agg(["count", "mean", "min", "max"])

      count       mean  min  max
dept
CSE       3  85.666667   78   91
ECE       2  60.000000   55   65
IT        1  72.000000   72   72

## 4. Group by two columns

In [8]:
df.groupby(["dept", "gender"])["marks"].mean()

dept  gender
CSE   F         89.5
      M         78.0
ECE   M         60.0
IT    F         72.0
Name: marks, dtype: float64

## 5. Pivot table - the same idea in table form

In [9]:
pd.pivot_table(df, values="marks", index="dept", columns="gender", aggfunc="mean")

gender     F     M
dept
CSE     89.5  78.0
ECE      NaN  60.0
IT      72.0   NaN

## Practice on the real data

In [10]:
students = pd.read_csv("data/students.csv")
students.groupby("dept")[["marks", "attendance"]].mean()

      marks  attendance
dept
CSE   81.00       90.50
ECE   77.80       88.60
IT    67.40       79.80
MECH  61.75       74.75

In [11]:
summary = students.groupby("city")["marks"].agg(["count", "mean"]).round(1)
summary.sort_values("mean", ascending=False)

            count  mean
city
Chennai         7  84.9
Coimbatore      4  73.8
Madurai         5  67.8
Trichy          4  57.8

## Try it yourself
1. Find the highest marks in each city.
2. How many male and female students are in each department?
3. Which department has the best average attendance?

In [12]:
# your code here